name: 'Notify frontend team on UI changes'
on:
 [push, pull_request]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check-for-UI-files:
    runs-on: "ubuntu-latest"
    
    env:
     PR_NUMBER: ${{ github.event.number }}

    steps:
      - name: 'checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: 'Get changed files'
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
         json: 'true'

      - name: 'List all changed files'
        id: notify
        uses: neil-empey/changes@v2.9
        with:
         emails: 'nempey2000@gmail.com'
         changed-files: ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Slack Notify
        id: slack 
        uses: slackapi/slack-github-action@v1.23.0
        with: |
          \"payload\": { \"pr\": "${{env.PR_NUMBER}}" }
        env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: email Marisa
        uses: cinotify/github-action@main
        with:
         to: 'nempey@eventpower.com'
         subject: "PR# ${{ env.PR_NUMBER }} needs your attention"
         body: "A PR needs your attention. PR# ${{ env.PR_NUMBER }}"
      
      - name: email Nick
        if: ${{ steps.notify.outputs.if-notified == 'true' }}
        uses: cinotify/github-action@main
        with:
         to: 'nrasp@eventpower.com'
         subject: ${{ steps.pr.outputs.pull_request_number }}
         body: 'A PR needs your attention. PR# ${{ steps.pr.outputs.pull_request_number }}'

      
