name: 'test'
on:
 push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check-links:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: 'checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Get changed files'
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: 'List all changed files'
        id: notify
        uses: neil-empey/changes@v2.6
        with:
         emails: 'nempey2000@gmail.com'
         changed-files: ${{ steps.changed-files.outputs.all_changed_files }}
         
      - name: Slack Notify
        if: ${{ steps.notify.outputs.if-notified == true }}
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        
      
