name: 'Notify frontend team on UI changes'
on:
 [push, pull_request]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check-for-UI-files:
    runs-on: "ubuntu-latest"
    
    env:
     PR_NUMBER: ${{ github.event.number }}

    steps:
      - name: 'checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: 'Get changed files'
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
         json: 'true'

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          #
          # Format:
          #
          #  * smtp://user:password@server:port
          #  * smtp+starttls://user:password@server:port
          connection_url: ${{secrets.MAIL_CONNECTION}}
          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended): mail server username:
          username: ${{nempey2000@gmail.com}}
          # Optional (recommended) mail server password:
          password: ${{Alaska_907}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: argus.two.2@gmail.com
          # Required sender full name (address can be skipped):
          from: Luke Skywalker # <user@example.com>
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          html_body: file://README.html
          # Optional carbon copy recipients:
          cc: nempey2000@gmail.com
          # Optional blind carbon copy recipients:
          #bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          #reply_to: luke@example.com
          # Optional Message ID this message is replying to:
          #in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          priority: high

      
