name: 'Notify frontend team on UI changes'
on:
 push:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check-for-UI-files:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: 'checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get Pull Request Number
        id: pr
        run: echo 'pull_request_number = $(gh pr view --json number -q .number)' >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Get changed files'
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
         json: 'true'

      - name: 'List all changed files'
        id: notify
        uses: neil-empey/changes@v2.9
        with:
         emails: 'nempey2000@gmail.com'
         changed-files: ${{ steps.changed-files.outputs.all_changed_files }}
         
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.1
        with:
          json: '{ "pr": ${{ steps.pr.outputs.pull_request_number }} }'

      - name: Slack Notify
        if: ${{ steps.notify.outputs.if-notified == 'true' }}
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with: |
          payload: ${{ steps.create-json.outputs.json }}
        env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: email Marisa
        if: ${{ steps.notify.outputs.if-notified == 'true' }}
        uses: cinotify/github-action@main
        with:
         to: 'marisa.mccarthy@eventpower.com'
         subject: ${{ steps.pr.outputs.pull_request_number }}
         body: 'A PR needs your attention. PR# ${{ steps.pr.outputs.pull_request_number }}'
      
      - name: email Nick
        if: ${{ steps.notify.outputs.if-notified == 'true' }}
        uses: cinotify/github-action@main
        with:
         to: 'nrasp@eventpower.com'
         subject: ${{ steps.pr.outputs.pull_request_number }}
         body: 'A PR needs your attention. PR# ${{ steps.pr.outputs.pull_request_number }}'

      
